services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    UserSessionBundle\Service\UserSessionManager:
        arguments:
            $entityClass: '%user_session.entity.class%'
            $dispatcher: '@event_dispatcher'
            $entityManager: '@doctrine.orm.entity_manager'
            $maxSessionsPerUser: '%user_session.max_sessions_per_user%'
            $updateThresholdSeconds: '%user_session.update_threshold%'

    UserSessionBundle\Subscriber\UserSessionSubscriber: 
        tags:
            - { name: 'kernel.event_subscriber' }

    UserSessionBundle\Security\RouteVoter:
        tags:
            - { name: security.voter }
            
    UserSessionBundle\Controller\UserSessionController:
        arguments:
            $sessionManager: '@UserSessionBundle\Service\UserSessionManager'
        tags: ['controller.service_arguments']
